# Generated by Django 3.2.7 on 2021-11-02 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='auction_listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bids',
            name='offer',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='auction_listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.CharField(default=1, max_length=640),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='current_bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default=1, max_length=640),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='lister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lister_listing', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='start_bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watch_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
