# Generated by Django 3.2.7 on 2021-11-04 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211103_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
